/**
 * Neomatrix Layer 0 — TARGETED PATCH for edited files (MON-131 D49).
 *
 * WHY THIS EXISTS. Layer 0 is regenerated by `graphify`, a local-only CLI that
 * is absent from CI *and* from the cloud dev containers this programme runs in
 * (`graphify-layer0.mjs` says so in its own header). But every file MON-131
 * touches is Layer-1 anchored, so any migration trips two gates at once:
 *   · ANCHORED DRIFT — `check-layer0-coverage.mjs` rehashes each covered file
 *     and hard-fails when one a semantic node describes has changed; and
 *   · the symbol-anchor gate, which resolves a Layer-1 `file:line` against the
 *     source (D49 option A, decided 2026-08-03).
 * D49 recorded the consequence in one line: "the migration pays this tax per
 * file." It was paid twice by hand first — d5c9434f (MON-140) established the
 * targeted-patch precedent and 4aab376e (MON-143) repeated it — each time with
 * a throwaway script. This is that operation, committed, so the third tranche
 * does not re-derive it and the fourth cannot do it sloppily.
 *
 * WHAT IT DOES. For each file changed between `--base` (default HEAD) and the
 * working tree:
 *   1. builds an old→new line map from `git diff -U0` hunks;
 *   2. shifts every Layer-0 node and edge line for that file;
 *   3. VERIFIES each shifted node lands on a line that actually contains its
 *      symbol, in the CURRENT source; and
 *   4. rehashes the content manifest for that file.
 *
 * WHAT MAKES IT HONEST, and the distinction the MON-143 commit had to draw
 * after getting it wrong once: a manifest rehash ALONE would silence the gate
 * while leaving the artifact stale — that is fitting the evidence to the test.
 * This refuses to write unless EVERY node in every touched file re-verifies
 * against source, including the nodes no gate inspects. A patch that moved only
 * the gated anchors would pass CI and leave Layer 0 selectively true, which is
 * worse than a red build because it reads green.
 *
 * WHAT IT IS NOT. Not a substitute for `npm run neomatrix:graphify`. It moves
 * lines that already exist; it cannot discover a symbol that was ADDED, and it
 * will not invent nodes for a NEW file — both are reported and left for a real
 * extraction (or the reviewed coverage allowlist). `_meta.builtAtCommit` is
 * deliberately left alone: the graph really was built there, and overwriting it
 * would be the same lie as a bare rehash.
 *
 * GHOSTS. A node whose symbol is absent from its whole file describes code that
 * no longer exists — Layer 0 asserting something false. That is not a shift
 * failure and must not be shifted anywhere; it is reported separately and
 * deleted only under `--prune-ghosts`, so removing a node from the map is
 * always a deliberate act. The first run found one: `adjustPropertyRentalIncome()`,
 * deleted by T1-B in 86f467f (there is even a test asserting the source no
 * longer contains it), still carried in Layer 0 with three edges. No gate had
 * noticed, because the coverage gate reconciles FILES and hashes, never symbols.
 *
 * Usage:  node scripts/neomatrix/patch-layer0.mjs [--base <rev>] [--dry-run] [--prune-ghosts]
 */

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { ROOTS, isSourceFile } from './roots.mjs';

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dir, '../..');
const OUT_DIR = resolve(ROOT, 'docs/financial-logic/graph/structural');
const GRAPH = resolve(OUT_DIR, 'structural-graph.json');
const MANIFEST = resolve(OUT_DIR, 'content-manifest.json');

const argv = process.argv.slice(2);
const DRY = argv.includes('--dry-run');
const PRUNE = argv.includes('--prune-ghosts');
const base = argv.includes('--base') ? argv[argv.indexOf('--base') + 1] : 'HEAD';

// MUST match graphify-layer0.mjs / check-layer0-coverage.mjs exactly: the
// manifest stores sha256 truncated to 16 hex (`_meta.algorithm: "sha256:16"`).
// Writing the full digest here produced a hash that could never compare equal,
// so the gate kept reporting drift on files this tool had just rehashed.
const sha = (buf) => createHash('sha256').update(buf).digest('hex').slice(0, 16);
const git = (args) => execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' });

/**
 * old line → new line, from `git diff -U0`. Returns null for a line inside a
 * deleted hunk: a node anchored to deleted code cannot be "shifted" anywhere
 * honest, and the verify pass below turns that into a refusal rather than a
 * silent drop.
 */
function lineMapFor(file) {
  let out;
  try {
    out = git(['diff', '-U0', base, '--', file]);
  } catch {
    return null;
  }
  const hunks = [];
  for (const line of out.split('\n')) {
    const m = /^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@/.exec(line);
    if (m) {
      hunks.push({
        oldStart: +m[1],
        oldLen: m[2] === undefined ? 1 : +m[2],
        newStart: +m[3],
        newLen: m[4] === undefined ? 1 : +m[4],
      });
    }
  }
  return (oldLine) => {
    let delta = 0;
    for (const h of hunks) {
      if (h.oldStart + h.oldLen <= oldLine) {
        delta += h.newLen - h.oldLen;
      } else if (h.oldStart <= oldLine) {
        return null; // inside the changed hunk — cannot be shifted mechanically
      } else {
        break;
      }
    }
    return oldLine + delta;
  };
}

/** The identifier a Layer-0 label stands for: `computePropertyCashflow()` → `computePropertyCashflow`. */
const symbolOf = (label) => String(label).replace(/\(\)\s*$/, '').trim();

/**
 * Re-locate a node whose mechanical shift missed. Searches the current source
 * for a DECLARATION of the symbol and takes the candidate nearest the shifted
 * guess. Still subject to the verify pass — this widens the search, it never
 * relaxes the proof.
 */
function relocate(lines, symbol, guess) {
  const decl = new RegExp(
    `\\b(?:function|class|interface|type|enum|const|let|var)\\s+${symbol}\\b|\\b${symbol}\\s*[(:=<]`,
  );
  const hits = [];
  for (let i = 0; i < lines.length; i++) if (decl.test(lines[i])) hits.push(i + 1);
  if (!hits.length) return null;
  return hits.reduce((best, h) => (Math.abs(h - guess) < Math.abs(best - guess) ? h : best), hits[0]);
}

const graph = JSON.parse(readFileSync(GRAPH, 'utf8'));
const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));

const changed = git(['diff', '--name-only', base])
  .split('\n')
  .map((s) => s.trim())
  .filter(Boolean)
  .filter((f) => isSourceFile(f) && ROOTS.some((r) => f === r || f.startsWith(`${r}/`)));

if (!changed.length) {
  console.log('Layer-0 patch: no source files changed since', base, '— nothing to do.');
  process.exit(0);
}

const ALLOWLIST = resolve(OUT_DIR, 'coverage-allowlist.json');
const allowed = new Set(
  existsSync(ALLOWLIST) ? Object.keys(JSON.parse(readFileSync(ALLOWLIST, 'utf8')).files || {}) : [],
);

const known = new Set(graph.files || []);
// An allowlisted file is not "new" — it is a reviewed, reasoned absence.
const newFiles = changed.filter((f) => !known.has(f) && !allowed.has(f));
const touched = changed.filter((f) => known.has(f) && existsSync(resolve(ROOT, f)));

const failures = [];
const ghosts = [];
const moved = [];

for (const file of touched) {
  const map = lineMapFor(file);
  if (!map) {
    failures.push(`${file}: could not read a diff against ${base}`);
    continue;
  }
  const lines = readFileSync(resolve(ROOT, file), 'utf8').split('\n');

  for (const node of graph.nodes) {
    if (node[2] !== file) continue;
    const oldLine = node[3];
    let next = map(oldLine);
    const symbol = symbolOf(node[1]);
    const lands = (ln) => ln >= 1 && ln <= lines.length && lines[ln - 1].includes(symbol);

    // A file-level node sits on line 1 by construction and names the file, not
    // a symbol in it — nothing to verify, nothing to move.
    if (oldLine === 1 && symbol.includes('.')) continue;

    if (next === null || !lands(next)) {
      const found = relocate(lines, symbol, next ?? oldLine);
      if (found !== null && lands(found)) {
        next = found;
      } else if (found === null) {
        // No DECLARATION of the symbol anywhere in the file — this node
        // describes code that has been DELETED. Not a shift failure; a false
        // statement in the map. (Deliberately "no declaration" rather than "the
        // text does not appear": the deleted function's name usually survives
        // in a comment explaining that it was deleted, which a plain substring
        // test would read as still present.)
        ghosts.push({ file, node, why: 'no declaration of the symbol anywhere in the file' });
        continue;
      } else {
        failures.push(
          `${file}:${oldLine} "${node[1]}" — shifted to ${next ?? 'deleted-hunk'}, which does not contain the symbol, and no declaration re-located it`,
        );
        continue;
      }
    }
    if (next !== oldLine) {
      moved.push(`${file}: ${node[1]} ${oldLine} → ${next}`);
      node[3] = next;
    }
  }

  // Edges carry the line of a call/reference site, not of a declaration, so
  // there is no symbol to assert them against. They are shifted by the same map
  // and any that fall inside a changed hunk are pinned to the hunk start rather
  // than guessed — stated plainly because it is the one part of this patch that
  // is approximate.
  for (const edge of graph.edges) {
    if (edge[3] !== file) continue;
    const next = map(edge[4]);
    if (next !== null && next !== edge[4]) edge[4] = next;
  }

  manifest.hashes[file] = sha(readFileSync(resolve(ROOT, file)));
}

for (const line of moved) console.log('  ', line);
console.log(
  `Layer-0 patch: ${touched.length} file(s) touched · ${moved.length} node line(s) moved · ${newFiles.length} new file(s)`,
);

if (newFiles.length) {
  console.log('\n  NEW source files — this tool will NOT invent nodes for them:');
  for (const f of newFiles) console.log('   -', f);
  console.log(
    '  Either run `npm run neomatrix:graphify` where the CLI exists, or add them to\n' +
      '  structural/coverage-allowlist.json with a reason a reviewer can check.',
  );
}

if (ghosts.length) {
  console.log('\n  GHOST NODES — Layer 0 describes code that no longer exists:');
  for (const g of ghosts) console.log(`   - ${g.file}:${g.node[3]} "${g.node[1]}" (${g.why})`);
  if (PRUNE) {
    const ids = new Set(ghosts.map((g) => g.node[0]));
    const beforeN = graph.nodes.length;
    const beforeE = graph.edges.length;
    graph.nodes = graph.nodes.filter((n) => !ids.has(n[0]));
    graph.edges = graph.edges.filter((e) => !ids.has(e[1]) && !ids.has(e[2]));
    console.log(
      `  pruned ${beforeN - graph.nodes.length} node(s) + ${beforeE - graph.edges.length} edge(s)`,
    );
  } else {
    console.error(
      '\n✗ REFUSING TO WRITE — re-run with --prune-ghosts to delete them, or restore the code.\n' +
        '  Deleting a node from the map is deliberate, never a side effect of a line shift.',
    );
    process.exit(1);
  }
}

if (failures.length) {
  console.error('\n✗ REFUSING TO WRITE — these nodes did not re-verify against source:');
  for (const f of failures) console.error('   -', f);
  console.error(
    '\n  Fix the graph by hand or regenerate Layer 0. A partial patch that silences\n' +
      '  the gate while leaving other nodes stale is the failure mode this refuses.',
  );
  process.exit(1);
}

if (DRY) {
  console.log('\n(dry run — nothing written)');
  process.exit(0);
}

writeFileSync(GRAPH, `${JSON.stringify(graph, null, 2)}\n`);
writeFileSync(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`);
console.log('\n✓ wrote structural-graph.json + content-manifest.json (builtAtCommit left honest)');
