'use client';

/**
 * MarginTrendLens — Phase 43.3
 *
 * The "GP-margin direction matters more than the absolute" rule from
 * Stark Naked Numbers (Andrew, Principle 2 — Maximize Your Margins),
 * translated to personal finance: a 6-month savings-rate sparkline +
 * delta-from-last-month on `/dashboard/budget-analysis`. The
 * direction is the load-bearing insight; the absolute number is
 * context.
 *
 * Why this surface exists: the existing budget-analysis page is
 * generated by AI as a one-shot estimate. Useful for *planning*,
 * useless for *progress*. The user has no way to answer *"am I
 * actually getting better at this over time?"* This lens does, in
 * one number + one curve.
 *
 * SSOT contract:
 *   - All values come from `/api/dashboard/margin-trend`, which
 *     queries `prisma.unifiedTransaction` directly grouped by month.
 *     The lens computes nothing — the route does the bucketing,
 *     trend-direction, and delta math.
 *   - No `quickMetrics` field added (D-43.3-2): trend is a *time
 *     series*, not a point-in-time number. The current `quickMetrics`
 *     SSOT is for current state.
 *
 * Design contract:
 *   - **Typography-led card**, same family as `HiddenWealthLens` +
 *     `SpendingParetoLens`. Subtle border + faint background. Apple
 *     restraint.
 *   - **Pure-SVG sparkline**, no chart library. ~280×64 viewbox; line
 *     stroke + faint area fill below. Trend tone driven by direction:
 *     emerald (up — Bandura victory tone), amber (down — never red,
 *     loss aversion), slate (flat).
 *   - **Self-hides when `enoughHistory === false`** — < 3 months with
 *     income, the data isn't there to draw a trend honestly.
 *   - **No red anywhere**, even on a downward trend. Down is amber,
 *     same warm-words rule the rest of the Stark-Naked-Numbers stack
 *     uses.
 *   - **Reduced-motion-safe** — the sparkline path-draw animation
 *     suppresses under `prefers-reduced-motion`, the line still
 *     renders.
 *
 * Behavioural-psychology contract (registered in 06_UI_UX_FOUNDATION.md):
 *   - **Direction-over-absolute** framing: closing copy says *"a few
 *     months of upward trend compounds dramatically over decades"* —
 *     the user is anchored to the *slope*, not the intercept.
 *   - **Locus-of-control** copy on flat/down trends: *"steady"* /
 *     *"a temporary dip is not a verdict"*. Never prescriptive.
 *   - **No celebratory language on up trends** that overstates a
 *     short streak. Kahneman warns against narrative fallacies on
 *     small samples; the copy stays measured.
 *
 * @see docs/blueprint/PHASE_43_3_MARGIN_TREND.md
 * @see app/api/dashboard/margin-trend/route.ts
 */

import { motion } from 'framer-motion';
import { TrendingUp, TrendingDown, Minus } from 'lucide-react';
import { formatCurrency } from '@/lib/utils/formatters';
import { appleEase, useReducedMotionSafe } from '@/components/shell';

export interface MarginTrendMonthProp {
  month: string;
  monthStart: string;
  monthlyIncome: number;
  monthlyExpense: number;
  netCashflow: number;
  savingsRate: number;
}

export interface MarginTrendLensProps {
  months: MarginTrendMonthProp[];
  current: MarginTrendMonthProp | null;
  previous: MarginTrendMonthProp | null;
  savingsRateDelta: number | null;
  netCashflowDelta: number | null;
  trend: 'up' | 'down' | 'flat';
  enoughHistory: boolean;
  monthsWithIncome: number;
}

/**
 * Format a year-month key like "2026-04" into a short tick label
 * like "Apr". UTC-safe.
 */
function shortMonthLabel(monthKey: string): string {
  const [y, m] = monthKey.split('-').map(Number);
  if (!y || !m) return monthKey;
  // Construct UTC midnight of the 1st to dodge timezone-day-rollover.
  const d = new Date(Date.UTC(y, m - 1, 1));
  return d.toLocaleString('en-AU', { month: 'short', timeZone: 'UTC' });
}

/**
 * Stoic, direction-honest closing copy. Never prescriptive. The
 * locus-of-control framing is "this is what's happening; you
 * decide what to do about it".
 */
function getClosingCopy(trend: 'up' | 'down' | 'flat'): string {
  switch (trend) {
    case 'up':
      return 'A few months of upward trend compounds dramatically over decades.';
    case 'down':
      return 'A temporary dip is not a verdict. The direction is what to watch.';
    case 'flat':
      return 'Steady. The direction matters more than the absolute — a small upward shift over time is the move.';
  }
}

/**
 * Tone palette per trend. No red anywhere — down trend uses amber
 * (loss-aversion-safe). Same family as `HiddenWealthLens` (which
 * reserves emerald for "Liquid" as the Bandura victory tone).
 */
const TREND_PALETTE: Record<
  'up' | 'down' | 'flat',
  {
    accentText: string;
    pillBg: string;
    pillText: string;
    sparkStroke: string;
    sparkFill: string;
    icon: typeof TrendingUp;
    label: string;
  }
> = {
  up: {
    accentText: 'text-emerald-700 dark:text-emerald-300',
    pillBg: 'bg-emerald-50 dark:bg-emerald-950/30',
    pillText: 'text-emerald-700 dark:text-emerald-300',
    sparkStroke: 'stroke-emerald-500 dark:stroke-emerald-400',
    sparkFill: 'fill-emerald-500/10 dark:fill-emerald-400/12',
    icon: TrendingUp,
    label: 'trending up',
  },
  down: {
    accentText: 'text-amber-700 dark:text-amber-300',
    pillBg: 'bg-amber-50 dark:bg-amber-950/30',
    pillText: 'text-amber-700 dark:text-amber-300',
    sparkStroke: 'stroke-amber-500 dark:stroke-amber-400',
    sparkFill: 'fill-amber-500/10 dark:fill-amber-400/12',
    icon: TrendingDown,
    label: 'trending down',
  },
  flat: {
    accentText: 'text-slate-700 dark:text-slate-300',
    pillBg: 'bg-slate-100 dark:bg-slate-800/40',
    pillText: 'text-slate-700 dark:text-slate-300',
    sparkStroke: 'stroke-slate-500 dark:stroke-slate-400',
    sparkFill: 'fill-slate-500/10 dark:fill-slate-400/12',
    icon: Minus,
    label: 'steady',
  },
};

/**
 * Build SVG sparkline path data from a series of savings rates.
 * Uses a fixed viewBox so the visual proportions stay stable
 * regardless of container width.
 */
function buildSparkPath(
  rates: number[],
  width: number,
  height: number,
  pad: number,
): { line: string; area: string } {
  if (rates.length < 2) return { line: '', area: '' };

  const min = Math.min(...rates, 0);
  const max = Math.max(...rates, 0);
  const range = max - min || 1;

  const innerW = width - pad * 2;
  const innerH = height - pad * 2;

  const pts = rates.map((v, i) => {
    const x = pad + (i / (rates.length - 1)) * innerW;
    // Invert y because SVG origin is top-left. Negative rates clamp
    // to the bottom of the chart so the line never disappears.
    const y = pad + innerH - ((v - min) / range) * innerH;
    return [x, y] as const;
  });

  const line = pts
    .map(([x, y], i) => `${i === 0 ? 'M' : 'L'} ${x.toFixed(2)} ${y.toFixed(2)}`)
    .join(' ');

  const baselineY = height - pad;
  const area =
    `M ${pts[0][0].toFixed(2)} ${baselineY.toFixed(2)} ` +
    pts.map(([x, y]) => `L ${x.toFixed(2)} ${y.toFixed(2)}`).join(' ') +
    ` L ${pts[pts.length - 1][0].toFixed(2)} ${baselineY.toFixed(2)} Z`;

  return { line, area };
}

export function MarginTrendLens({
  months,
  current,
  previous,
  savingsRateDelta,
  netCashflowDelta,
  trend,
  enoughHistory,
  monthsWithIncome,
}: MarginTrendLensProps) {
  const reduced = useReducedMotionSafe();

  if (!enoughHistory || !current || months.length < 2) return null;

  const palette = TREND_PALETTE[trend];
  const TrendIcon = palette.icon;

  const SVG_WIDTH = 320;
  const SVG_HEIGHT = 72;
  const PAD = 6;
  const rates = months.map((m) => m.savingsRate);
  const { line, area } = buildSparkPath(rates, SVG_WIDTH, SVG_HEIGHT, PAD);

  // Delta string: "+3 points" / "−2 points" / "no change". Rounded
  // to 1pp because anything finer is noise on transactional data.
  const deltaPP =
    savingsRateDelta !== null ? Math.round(savingsRateDelta) : null;
  const deltaText =
    deltaPP === null
      ? null
      : deltaPP > 0
        ? `+${deltaPP} ${deltaPP === 1 ? 'point' : 'points'} vs last month`
        : deltaPP < 0
          ? `${deltaPP} ${Math.abs(deltaPP) === 1 ? 'point' : 'points'} vs last month`
          : 'no change vs last month';

  const cashflowDeltaText =
    netCashflowDelta !== null
      ? `${netCashflowDelta >= 0 ? '+' : '−'}${formatCurrency(Math.abs(netCashflowDelta), { showCents: false })} in net cashflow`
      : null;

  return (
    <section
      aria-label="How your margin is trending"
      className="rounded-3xl border border-foreground/[0.06] bg-foreground/[0.015] px-5 py-6 sm:px-7 sm:py-7"
    >
      {/* Eyebrow + window-size meta. */}
      <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
        <h2 className="text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">
          How your margin is trending
        </h2>
        <p className="text-xs tabular-nums text-muted-foreground">
          {months.length} months · {monthsWithIncome} with income
        </p>
      </div>

      {/* Headline + trend pill. The headline is the *current* savings
          rate; the pill anchors the user to the *direction*. */}
      <div className="mt-3 flex flex-wrap items-baseline gap-3">
        <div className="flex items-baseline gap-2">
          <span
            className={`text-4xl font-semibold tracking-tight tabular-nums sm:text-5xl ${palette.accentText}`}
          >
            {Math.round(current.savingsRate)}%
          </span>
          <span className="text-sm text-muted-foreground">
            kept this month
          </span>
        </div>
        <span
          className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold ${palette.pillBg} ${palette.pillText}`}
        >
          <TrendIcon className="h-3 w-3" aria-hidden />
          {palette.label}
        </span>
      </div>

      {/* Delta strip — savings-rate change in points + dollars in net.
          Two-axis honesty: same direction can look different in $ vs %. */}
      {(deltaText || cashflowDeltaText) && (
        <p className="mt-2 text-sm text-muted-foreground">
          {deltaText && <span>{deltaText}</span>}
          {deltaText && cashflowDeltaText && (
            <span className="mx-1.5 opacity-50">·</span>
          )}
          {cashflowDeltaText && <span>{cashflowDeltaText}</span>}
        </p>
      )}

      {/* The sparkline. Pure SVG — no chart library. The line +
          faint area fill encode trend visually; tick labels under
          the chart anchor each point to a calendar month. */}
      <div className="mt-6">
        <svg
          viewBox={`0 0 ${SVG_WIDTH} ${SVG_HEIGHT}`}
          width="100%"
          height={SVG_HEIGHT}
          aria-hidden
          className="overflow-visible"
        >
          {/* Subtle baseline grid — single horizontal at midpoint */}
          <line
            x1={PAD}
            x2={SVG_WIDTH - PAD}
            y1={SVG_HEIGHT / 2}
            y2={SVG_HEIGHT / 2}
            className="stroke-foreground/[0.06]"
            strokeDasharray="2 4"
          />

          {/* Area fill below the line, faint */}
          <motion.path
            d={area}
            className={palette.sparkFill}
            initial={reduced ? { opacity: 1 } : { opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={
              reduced
                ? { duration: 0 }
                : { duration: 0.6, ease: appleEase, delay: 0.2 }
            }
          />

          {/* The line itself */}
          <motion.path
            d={line}
            className={`fill-none ${palette.sparkStroke}`}
            strokeWidth={1.75}
            strokeLinecap="round"
            strokeLinejoin="round"
            initial={
              reduced
                ? { pathLength: 1 }
                : { pathLength: 0 }
            }
            animate={{ pathLength: 1 }}
            transition={
              reduced
                ? { duration: 0 }
                : { duration: 0.9, ease: appleEase, delay: 0.05 }
            }
          />

          {/* Last-point dot — anchors the eye to the current value */}
          {months.length > 0 && (() => {
            const idx = months.length - 1;
            const x =
              PAD + (idx / (months.length - 1)) * (SVG_WIDTH - PAD * 2);
            const min = Math.min(...rates, 0);
            const max = Math.max(...rates, 0);
            const range = max - min || 1;
            const y =
              PAD +
              (SVG_HEIGHT - PAD * 2) -
              ((current.savingsRate - min) / range) * (SVG_HEIGHT - PAD * 2);
            return (
              <motion.circle
                cx={x}
                cy={y}
                r={3}
                className={palette.sparkStroke.replace('stroke-', 'fill-')}
                initial={reduced ? { opacity: 1, scale: 1 } : { opacity: 0, scale: 0.4 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={
                  reduced
                    ? { duration: 0 }
                    : { duration: 0.4, ease: appleEase, delay: 0.95 }
                }
              />
            );
          })()}
        </svg>

        {/* Tick labels — month abbreviations under the chart. */}
        <div className="mt-2 flex justify-between px-1.5 text-[10px] tabular-nums text-muted-foreground">
          {months.map((m) => (
            <span key={m.month}>{shortMonthLabel(m.month)}</span>
          ))}
        </div>
      </div>

      {/* Closing copy — direction-over-absolute framing. Stoic. */}
      <p className="mt-5 max-w-prose text-[12px] text-muted-foreground">
        {getClosingCopy(trend)}
      </p>
    </section>
  );
}
